name: Run Vitest with Coverage

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: react-game  # ensures the commands run in your actual project folder

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci

      - name: Run Tests with Coverage
        run: npx vitest run --coverage

      - name: Upload HTML Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: coverage/report-html/
      
      - name: Upload LCOV Report
        uses: actions/upload-artifact@v4
        with:
          name: lcov-report
          path: coverage/lcov.info

      - name: Annotate with Test Summary
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Vitest Summary
          path: react-game/test-results.json
          reporter: jest-junit